SELECT INSTITUTION_NUMBER, CLIENT_NUMBER, GROUP_NUMBER, PARENT_CLIENT_NUMBER, CLIENT_TYPE, CLIENT_LEVEL,
MCC, CLIENT_COUNTRY, SERVICE_CONTRACT_ID, CLIENT_TARIFF, SETTLEMENT_METHOD, POSTING_METHOD, MERCHANT_TRAN_TARIFF,
LISTAGG(ACCOUNT_TYPE_ID, ',') WITHIN GROUP (ORDER BY ACCOUNT_TYPE_ID) AS ACCOUNT_TYPE_ID, ACCT_CURRENCY,
BILLING_LEVEL, STATEMENT_GENERATION, STATEMENT_TYPE, ADDRESS_CATEGORY, SERVICE_ID, FUNDING_CLIENT, DOMESTIC_MCC,
CLIENT_BRANCH, CLIENT_REGION, CLIENT_STATE, SEASONAL_INDICATOR, MC_IP_QUALIFICATION, MC_IP_VALUE, CONTRACT_STATUS
FROM ( SELECT
  NVL(DETL.INSTITUTION_NUMBER,'NULL') AS INSTITUTION_NUMBER,
  NVL(DETL.CLIENT_NUMBER,'NULL') AS CLIENT_NUMBER,
  NVL(LNKS.GROUP_NUMBER,'NULL') AS GROUP_NUMBER,
  NVL(LNKS.PARENT_CLIENT_NUMBER,'NULL') AS PARENT_CLIENT_NUMBER,
  NVL(DETL.CLIENT_TYPE,'NULL') AS CLIENT_TYPE,
  NVL(LNKS.CLIENT_LEVEL,'NULL') AS CLIENT_LEVEL,
  NVL(DETL.BUSINESS_CLASS,'NULL') AS MCC,
  NVL(DETL.CLIENT_COUNTRY,'NULL') AS CLIENT_COUNTRY,
  NVL(LNKS.SERVICE_CONTRACT_ID,'NULL') AS SERVICE_CONTRACT_ID,
  NVL(LNKS.CLIENT_TARIFF,'NULL') AS CLIENT_TARIFF,
  NVL(LNKS.SETTLEMENT_METHOD,'NULL') AS SETTLEMENT_METHOD,
  NVL(LNKS.POSTING_METHOD,'NULL') AS POSTING_METHOD,
  NVL(LNKS.MERCHANT_TRAN_TARIFF,'NULL') AS MERCHANT_TRAN_TARIFF,
  NVL(ACCT.ACCOUNT_TYPE_ID,'NULL') AS ACCOUNT_TYPE_ID,
  NVL(ACCT1.ACCT_CURRENCY,'NULL') AS ACCT_CURRENCY,
  NVL(ACCT.BILLING_LEVEL,'NULL') AS BILLING_LEVEL,
  NVL(ACCT.STATEMENT_GENERATION,'NULL') AS STATEMENT_GENERATION,
  NVL(ACCT.STATEMENT_TYPE,'NULL') AS STATEMENT_TYPE,
  NVL(ADDR.ADDRESS_CATEGORY,'NULL') AS ADDRESS_CATEGORY,
  NVL((CASE LNKS.CLIENT_LEVEL WHEN '001'
  		THEN
		   (SELECT 	LISTAGG(SERV.SERVICE_ID, ',') WITHIN GROUP (ORDER BY SERV.SERVICE_ID) AS SERVICE_ID
				FROM 		SVC_CLIENT_SERVICE SERV
				WHERE 	SERV.INSTITUTION_NUMBER = '00000111'
				AND 		DETL.INSTITUTION_NUMBER = SERV.INSTITUTION_NUMBER
				AND	 		DETL.CLIENT_NUMBER = SERV.CLIENT_NUMBER
				AND 		LNKS.SERVICE_CONTRACT_ID = SERV.SERVICE_CONTRACT_ID
				GROUP BY 	SERV.CLIENT_NUMBER, LNKS.SERVICE_CONTRACT_ID)
  		ELSE
  			(SELECT 'NULL' FROM DUAL)
  		END
	),'NULL') AS SERVICE_ID,
  (CASE WHEN ACCT1.SETTLEMENT_NUMBER > 0
  		THEN
		   (SELECT 	NVL(SETL.FUNDING_CLIENT,'NULL')
				FROM 		CAS_CLIENT_ACCOUNT ACCT2, CIS_SETTLEMENT_INFORMATION SETL
				WHERE 	ACCT2.INSTITUTION_NUMBER = '00000111'
				AND 		DETL.INSTITUTION_NUMBER = ACCT2.INSTITUTION_NUMBER
				AND 		DETL.INSTITUTION_NUMBER = SETL.INSTITUTION_NUMBER
				AND	 		DETL.CLIENT_NUMBER = ACCT2.CLIENT_NUMBER
				AND	 		ACCT2.CLIENT_NUMBER = SETL.CLIENT_NUMBER
				AND	 		ACCT2.SETTLEMENT_NUMBER = SETL.SETTLEMENT_NUMBER
				AND			ACCT2.ACCOUNT_TYPE_ID = ACCT.ACCOUNT_TYPE_ID
				AND	 		ACCT2.CLIENT_NUMBER = DETL.CLIENT_NUMBER
				AND			ACCT2.ACCT_NUMBER = ACCT1.ACCT_NUMBER
				AND 		ACCT2.BILLING_LEVEL = '001'
				GROUP BY ACCT2.ACCT_NUMBER, SETL.FUNDING_CLIENT)
  		ELSE
  			(SELECT 'NULL' FROM DUAL)
  		END
	) AS FUNDING_CLIENT,
  NVL(DETL.DOMESTIC_MCC,'NULL') AS DOMESTIC_MCC,
  NVL(LNKS.CLIENT_BRANCH,'NULL') AS CLIENT_BRANCH,
  NVL(DETL.CLIENT_REGION,'NULL') AS CLIENT_REGION,
  NVL(DETL.CLIENT_STATE,'NULL') AS CLIENT_STATE,
  NVL(ADDE.SEASONAL_INDICATOR,'NULL') AS SEASONAL_INDICATOR,
  NVL(DETL.MC_IP_QUALIFICATION,'NULL') AS MC_IP_QUALIFICATION,
  NVL(DETL.MC_IP_VALUE,'NULL') AS MC_IP_VALUE,
  NVL(LNKS.CONTRACT_STATUS,'NULL') AS CONTRACT_STATUS
FROM
  CIS_CLIENT_DETAILS DETL, CIS_CLIENT_LINKS LNKS, CIS_APPLICATION_DETAIL PRE,
  (SELECT LISTAGG(ADDR.ADDRESS_CATEGORY, ',') WITHIN GROUP (ORDER BY ADDR.ADDRESS_CATEGORY) AS ADDRESS_CATEGORY,
  				ADDR.CLIENT_NUMBER, LNKS.SERVICE_CONTRACT_ID, LNKS.CLIENT_LEVEL
   		 FROM CIS_ADDRESSES ADDR, CIS_CLIENT_DETAILS DETL, CIS_CLIENT_LINKS LNKS
   		WHERE ADDR.INSTITUTION_NUMBER = '00000111'
     		AND DETL.INSTITUTION_NUMBER = ADDR.INSTITUTION_NUMBER
     		AND DETL.INSTITUTION_NUMBER = LNKS.INSTITUTION_NUMBER
     		AND DETL.CLIENT_NUMBER = LNKS.CLIENT_NUMBER
     		AND DETL.CLIENT_NUMBER = ADDR.CLIENT_NUMBER
   GROUP BY ADDR.CLIENT_NUMBER, LNKS.SERVICE_CONTRACT_ID, LNKS.CLIENT_LEVEL
   ) ADDR,
  (SELECT
     LISTAGG(ACCT.ACCT_CURRENCY, ',') WITHIN GROUP (ORDER BY ACCT.ACCT_CURRENCY) AS ACCT_CURRENCY,
     ACCT.CLIENT_NUMBER, ACCT.BILLING_LEVEL, ACCT.STATEMENT_GENERATION, LNKS.SERVICE_CONTRACT_ID, LNKS.CLIENT_LEVEL, ACCT.SETTLEMENT_NUMBER, ACCT.ACCT_NUMBER
   FROM
     CAS_CLIENT_ACCOUNT ACCT, CIS_CLIENT_DETAILS DETL, CIS_CLIENT_LINKS LNKS
   WHERE
     ACCT.INSTITUTION_NUMBER = '00000111'  AND
     DETL.INSTITUTION_NUMBER = ACCT.INSTITUTION_NUMBER AND
     DETL.INSTITUTION_NUMBER = LNKS.INSTITUTION_NUMBER AND
     LNKS.SERVICE_CONTRACT_ID = ACCT.SERVICE_CONTRACT_ID AND
     DETL.CLIENT_NUMBER = ACCT.CLIENT_NUMBER AND
     DETL.CLIENT_NUMBER = LNKS.CLIENT_NUMBER
   GROUP BY
     ACCT.CLIENT_NUMBER, ACCT.ACCOUNT_TYPE_ID, LNKS.SERVICE_CONTRACT_ID, ACCT.BILLING_LEVEL, ACCT.STATEMENT_GENERATION, LNKS.CLIENT_LEVEL, ACCT.SETTLEMENT_NUMBER,ACCT.ACCT_NUMBER) ACCT1,
  (SELECT
     LISTAGG(ACCT.ACCOUNT_TYPE_ID, ',') WITHIN GROUP (ORDER BY ACCT.ACCOUNT_TYPE_ID) AS ACCOUNT_TYPE_ID, ACCT.ACCT_NUMBER,
     LNKS.SERVICE_CONTRACT_ID, ACCT.BILLING_LEVEL, ACCT.STATEMENT_GENERATION, ACCT.STATEMENT_TYPE, LNKS.CLIENT_LEVEL,
     ACCT.CLIENT_NUMBER
   FROM
     CAS_CLIENT_ACCOUNT ACCT, CIS_CLIENT_DETAILS DETL, CIS_CLIENT_LINKS LNKS
   WHERE
     ACCT.INSTITUTION_NUMBER = '00000111'  AND
     DETL.INSTITUTION_NUMBER = ACCT.INSTITUTION_NUMBER AND
     DETL.INSTITUTION_NUMBER = LNKS.INSTITUTION_NUMBER AND
     LNKS.SERVICE_CONTRACT_ID = ACCT.SERVICE_CONTRACT_ID AND
     DETL.CLIENT_NUMBER = ACCT.CLIENT_NUMBER AND
     DETL.CLIENT_NUMBER = LNKS.CLIENT_NUMBER
   GROUP BY
     ACCT.ACCT_CURRENCY, ACCT.BILLING_LEVEL, LNKS.CLIENT_LEVEL,
     ACCT.STATEMENT_GENERATION, ACCT.STATEMENT_TYPE, LNKS.SERVICE_CONTRACT_ID,
     ACCT.CLIENT_NUMBER, ACCT.ACCT_NUMBER) ACCT,
   (SELECT
	 ADDE.SEASONAL_INDICATOR, ADDE.CLIENT_NUMBER
	FROM
	 CIS_CLIENT_ADDENDUM ADDE, CIS_CLIENT_DETAILS DETL
	WHERE
	 ADDE.INSTITUTION_NUMBER = '00000111'  AND
	 ADDE.INSTITUTION_NUMBER = DETL.INSTITUTION_NUMBER AND
	 ADDE.CLIENT_NUMBER = DETL.CLIENT_NUMBER) ADDE
WHERE
  DETL.INSTITUTION_NUMBER = '00000111'  AND
  DETL.INSTITUTION_NUMBER = LNKS.INSTITUTION_NUMBER AND
  DETL.INSTITUTION_NUMBER = PRE.INSTITUTION_NUMBER AND
  LNKS.SERVICE_CONTRACT_ID = ACCT1.SERVICE_CONTRACT_ID AND
  LNKS.SERVICE_CONTRACT_ID = ACCT.SERVICE_CONTRACT_ID AND
  LNKS.SERVICE_CONTRACT_ID = ADDR.SERVICE_CONTRACT_ID AND
  LNKS.SERVICE_CONTRACT_ID = PRE.SERVICE_CONTRACT_ID AND
  DETL.CLIENT_STATUS = '001' AND
  PRE.APPLICATION_STATUS = '004' AND
  DETL.CLIENT_NUMBER = PRE.CLIENT_NUMBER AND
  DETL.CLIENT_NUMBER = ACCT.CLIENT_NUMBER AND
  DETL.CLIENT_NUMBER = ACCT1.CLIENT_NUMBER AND
  DETL.CLIENT_NUMBER = ADDR.CLIENT_NUMBER AND
  DETL.CLIENT_NUMBER = ADDE.CLIENT_NUMBER AND
  DETL.CLIENT_NUMBER = LNKS.CLIENT_NUMBER AND
  ACCT1.BILLING_LEVEL = ACCT.BILLING_LEVEL AND
  ACCT1.ACCT_NUMBER = ACCT.ACCT_NUMBER AND
 	ACCT1.STATEMENT_GENERATION = ACCT.STATEMENT_GENERATION AND
 	--DETL.CLIENT_NUMBER > SUBSTR('00000111',7,2)||'000999' AND
 	--DETL.CLIENT_NUMBER LIKE  SUBSTR('00000111',7,2)||'00%%'
 	 DETL.CLIENT_NUMBER in ('00000333','00000337','00000334','00000335')
GROUP BY
	DETL.INSTITUTION_NUMBER,DETL.CLIENT_NUMBER, LNKS.PARENT_CLIENT_NUMBER, LNKS.GROUP_NUMBER, DETL.CLIENT_TYPE,
  LNKS.CLIENT_LEVEL, DETL.BUSINESS_CLASS, DETL.CLIENT_COUNTRY,
  LNKS.SERVICE_CONTRACT_ID, LNKS.CLIENT_TARIFF, LNKS.SETTLEMENT_METHOD,
  LNKS.POSTING_METHOD, LNKS.MERCHANT_TRAN_TARIFF, ACCT1.ACCT_CURRENCY,
  ADDR.ADDRESS_CATEGORY, ACCT.ACCOUNT_TYPE_ID, ACCT.BILLING_LEVEL, ACCT1.SETTLEMENT_NUMBER, ACCT1.ACCT_NUMBER,
  ACCT.STATEMENT_GENERATION, ACCT.STATEMENT_TYPE, DETL.DOMESTIC_MCC, LNKS.CLIENT_BRANCH, DETL.CLIENT_REGION,
  DETL.CLIENT_STATE, ADDE.SEASONAL_INDICATOR, DETL.MC_IP_QUALIFICATION, DETL.MC_IP_VALUE, LNKS.CONTRACT_STATUS
ORDER BY DETL.CLIENT_NUMBER, LNKS.SERVICE_CONTRACT_ID, LNKS.PARENT_CLIENT_NUMBER, LNKS.CLIENT_LEVEL)
GROUP BY INSTITUTION_NUMBER,CLIENT_NUMBER,GROUP_NUMBER,PARENT_CLIENT_NUMBER,CLIENT_TYPE,CLIENT_LEVEL,
MCC,CLIENT_COUNTRY,SERVICE_CONTRACT_ID,CLIENT_TARIFF,SETTLEMENT_METHOD,POSTING_METHOD,MERCHANT_TRAN_TARIFF,
ACCT_CURRENCY,BILLING_LEVEL,STATEMENT_GENERATION,STATEMENT_TYPE,ADDRESS_CATEGORY,SERVICE_ID,FUNDING_CLIENT,
DOMESTIC_MCC,CLIENT_BRANCH,CLIENT_REGION,CLIENT_STATE,SEASONAL_INDICATOR,MC_IP_QUALIFICATION,MC_IP_VALUE, CONTRACT_STATUS
