export const Identifiers = {
    css: { name: "css", keyword: "001" },
    xpath: { name: "xpath", keyword: "002" },
    id: { name: "id", keyword: "003" },
    linktext: { name: "linktext", keyword: "004" },
    tagname: { name: "tagname", keyword: "005" },
    classname: { name: "classname", keyword: "006" },
}

export const Commands = {
    InputText: { name: "InputText", keyword: "001" },
    ClickElement: { name: "ClickElement", keyword: "002" },
    StoreAttribute: { name: "StoreAttribute", keyword: "003" },
    MouseOver: { name: "MouseOver", keyword: "004" },
    SwitchToWindow: { name: "SwitchToWindow", keyword: "005" },
    SwitchToFrame: { name: "SwitchToFrame", keyword: "006" },
    DoubleClick : { name: "DoubleClick", keyword: "007" },
    DragAndDrop : { name: "DragAndDrop", keyword: "008" },
    RightClickElement : { name: "RightClickElement", keyword: "009" },
    ClickUsingJavaScript : { name: "ClickUsingJavaScript", keyword: "010" },
    EnterTextUsingJavaScript : { name: "EnterTextUsingJavaScript", keyword: "011" },
    AssertWindowTitle : { name: "AssertWindowTitle", keyword: "012" },
    AssertElementText   : { name: "AssertElementText", keyword: "013" },
    AssertElementOnPage : { name: "AssertElementOnPage", keyword: "014" },
    KeyboardPressKeys : { name: "KeyboardPressKeys", keyword: "015" },
    SelectByValueFromDropdown : { name: "SelectByValueFromDropdown", keyword: "016" },
    SelectByIndexFromDropdown : { name: "SelectByIndexFromDropdown", keyword: "017" },
    SelectByVisibleTextFromDropdown : { name: "SelectByVisibleTextFromDropdown", keyword: "018" },
    DeSelectByIndexFromDropdown : { name: "DeSelectByIndexFromDropdown", keyword: "019" },
    DeSelectByVisibleTextFromDropdown : { name: "DeSelectByVisibleTextFromDropdown", keyword: "020" },
    DeSelectByValueFromDropdown : { name: "DeSelectByValueFromDropdown", keyword: "021" },
    DeSelectAllFromDropdown : { name: "DeSelectAllFromDropdown", keyword: "022" },
    UploadFile : { name: "UploadFile", keyword: "023" },
    SwitchToAlertWindowAccept : { name: "SwitchToAlertWindowAccept", keyword: "024" },
    SwitchToAlertWindowDismiss : { name: "SwitchToAlertWindowDismiss", keyword: "025" },
    ClearContent : { name: "ClearContent", keyword: "026" },
    TakeScreenshot : { name: "TakeScreenshot", keyword: "027" },
    SelectRadioButton : { name: "SelectRadioButton", keyword: "028" },
    DeSelectRadioButton : { name: "DeSelectRadioButton", keyword: "029" },
    OpenBrowser : { name: "OpenBrowser", keyword: "030" },
    NavigateToURL: { name: "NavigateToURL", keyword: "031" },
    RefreshBrowser : { name: "RefreshBrowser", keyword: "032" },
    CloseBrowser : { name: "CloseBrowser", keyword: "033" },
    MaximizeBrowser : { name: "MaximizeBrowser", keyword: "034" },
    StaticWait: { name: "StaticWait", keyword: "035" },
    SelectCheckBox : { name: "SelectCheckBox", keyword: "036" },
    DeSelectCheckBox : { name: "DeSelectCheckBox", keyword: "037" },
    DeleteAllCookies : { name: "DeleteAllCookies", keyword: "038" },
    GetElementAttribute : { name: "GetElementAttribute", keyword: "039" },
    GetWindowsCurrentURL : { name: "GetWindowsCurrentURL", keyword: "040" },
    SelectAllOptionsFromDropdown : { name: "SelectAllOptionsFromDropdown", keyword: "041" },
    AssertElementDisplayed : { name: "AssertElementDisplayed", keyword: "042" },
    WaitTillElementNotVisible : { name: "WaitTillElementNotVisible", keyword: "043" },
    DownloadFile : { name: "DownloadFile", keyword: "044" },
    AssertElementEnabled : { name: "AssertElementEnabled", keyword: "045" }, 
    AssertElementDisabled : { name: "AssertElementDisabled", keyword: "046" },
    ScrollPageByCoOrdinates : { name: "ScrollPageByCoOrdinates", keyword: "047" },
    WaitTillElementVisible : { name: "WaitTillElementVisible", keyword: "048" },
    CheckForPageLoad : { name: "CheckForPageLoad", keyword: "049" },
    AssertElementAttributeValueContains : { name: "AssertElementAttributeValueContains", keyword: "050" },
    AssertElementAttributeValueDoesNotContains : { name: "AssertElementAttributeValueDoesNotContains", keyword: "051" },
    InputDataWithCurrentDateAndTime : { name: "InputDataWithCurrentDateAndTime", keyword: "052" },
    AssertElementTextWithInputData : { name: "AssertElementTextWithInputData", keyword: "053" },
    AssertElementTextNotContains : { name: "AssertElementTextNotContains", keyword: "054" },
    AssertElementTextContains : { name: "AssertElementTextContains", keyword: "055" },
    AssertTextBasedOnRegex : { name: "AssertTextBasedOnRegex", keyword: "056" },
    AssertElementNotDisplayed  : { name: "AssertElementNotDisplayed", keyword: "057" },
    SelectDateFromDatePicker : { name: "SelectDateFromDatePicker", keyword: "058" },
    SelectDateRangeFromDatePicker : { name: "SelectDateRangeFromDatePicker", keyword: "059" },
    AssertStoredAttributeEquals : { name: "AssertStoredAttributeEquals", keyword: "060" },
    AssertStoredAttributeNotEquals : { name: "AssertStoredAttributeNotEquals", keyword: "061" },
    EnterStoredTextWithRandomNumber : { name: "EnterStoredTextWithRandomNumber", keyword: "062" },
    AssertStoredAttributeContains : { name: "AssertStoredAttributeContains", keyword: "063" },
    AssertStoredAttributeNotContains : { name: "AssertStoredAttributeNotContains", keyword: "064" },
    AssertElementAttributeContainsStoredAttribute : { name: "AssertElementAttributeContainsStoredAttribute", keyword: "065" },
    AssertCurrentURL: { name: "AssertCurrentURL", keyword: "066" },
    AssertCurrentURLContains : { name: "AssertCurrentURLContains", keyword: "067" },
    SwitchToMainWindow : { name: "SwitchToMainWindow", keyword: "068" },
    AssertElementHavingStoreAttributeText : { name: "AssertElementHavingStoreAttributeText", keyword: "069" },
    
    ExecuteSQL : { name: "ExecuteSQL", keyword: "900" },
    ExecuteStoredProcedure : { name: "ExecuteStoredProcedure", keyword: "901" },
    ExecuteTestFile : { name: "ExecuteTestFile", keyword: "902" },
    ExecuteTestAPI : { name: "ExecuteTestAPI", keyword: "903" },
}